"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Anthony Dezdha and Saul Marenco, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1:AD54489
UT EID 2:
"""


class Node:
    """
    A modified version of the Node class for linked lists (using proper class
    coding practices). Instead of a data instance variable, this node class has both
    a coefficient and an exponent instance variable, which is used to represent each
    term in a polynomial.
    """

    def __init__(self, coeff, exp, link=None):
        """
        Node Constructor for polynomial linked lists.

        Args:
        - coeff: The coefficient of the term.
        - exp: The exponent of the term.
        - link: The next node in the linked list.
        """
        self.coeff = coeff
        self.exp = exp
        self.next = link

    @property
    def coeff(self):
        """
        Getter method for the coefficient attribute.
        """
        return self.__coeff

    @coeff.setter
    def coeff(self, value):
        """
        Setter method for the coefficient attribute.
        """
        if value is None or isinstance(value, int):
            self.__coeff = value
        else:
            raise ValueError("Coefficient must be an integer or None.")

    @property
    def exp(self):
        """
        Getter method for the exponent attribute.
        """
        return self.__exp

    @exp.setter
    def exp(self, value):
        """
        Setter method for the exponent attribute.
        """
        if value is None or isinstance(value, int):
            self.__exp = value
        else:
            raise ValueError("Exponent must be an integer or None.")

    @property
    def next(self):
        """
        Getter method for the next attribute.
        """
        return self.__next

    @next.setter
    def next(self, value):
        """
        Setter method for the next attribute.
        """
        if value is None or isinstance(value, Node):
            self.__next = value
        else:
            raise ValueError("Next must be a Node instance or None.")

    def __str__(self):
        """
        String representation of each term in a polynomial linked list.
        """
        return f"({self.coeff}, {self.exp})"


class LinkedList:
    def __init__(self):
        # You are also welcome to use a sentinel/dummy node!
        # It is definitely recommended, which will we learn more
        # about in class on Monday 3/24. If you choose to use
        # a dummy node, comment out the self.head = None
        # and comment in the below line. We use None to make sure
        # if there is an error where you accidentally include the
        # dummy node in your calculation, it will throw an error.
        # self.dummy = Node(None, None)
        self.head = None

    # Insert the term with the coefficient coeff and exponent exp into the polynomial.
    # If a term with that exponent already exists, add the coefficients together.
    # You must keep the terms in descending order by exponent.
    def insert_term(self, coeff, exp):
        #recursive insert, descending order,
        if coeff == 0:
            return
        self.head = self.insert_term_helper(self.head, coeff, exp)
    def insert_term_helper(self, node, coeff, exp):
        if node is None:
            return Node(coeff, exp)
        elif exp > node.exp:
            one_node = Node(coeff, exp)
            one_node.next = node
            return one_node
        elif exp == node.exp:
            node.coeff += coeff
            if node.coeff == 0:
                return node.next
            else:
                return node
        else:
            node.next = self.insert_term_helper(node.next, coeff, exp)
            return node

    # Add a polynomial p to the polynomial and return the resulting polynomial as a new linked list.
    def add(self, p):
        pass

    # Multiply a polynomial p with the polynomial and return the product as a new linked list.
    def mult(self, p):
        product = LinkedList()
        first_it = self.head
        while first_it:
            partial = LinkedList()
            second_it = p.head
            while second_it:
                nuovo_coeff = first_it.coeff * second_it.coeff
                nuovo_exp = first_it.exp + second_it.exp
                partial.insert_term(nuovo_coeff, nuovo_exp)
                second_it = second_it.next
            product = product.add(partial)
            first_it = first_it.next
        return product




    # Return a string representation of the polynomial.
    def __str__(self):
        pass


def main():
    # read data from stdin (terminal/file) using input() and create polynomial p
    countP = int(input().strip())
    polyP = LinkedList()
    for i in range(countP):
        parts, coeff, exp, line = line.split(), int(parts[0]), int(parts[1]), input().strip()
        polyP.insert_term(coeff, exp)
    # read data from stdin (terminal/file) using input() and create polynomial q
    input()
    countQ = int(input().strip())
    polyQ = linkedList()
    for i in range(countQ):
        parts, coeff, exp, line = line.split(), int(parts[0]), int(parts[1]), input().strip()
        polyQ.insert_term(coeff, exp)
    # get sum of p and q as a new linked list and print sum
    sumPoly = polyP.add(polyQ)
    print(sumPoly)
    # get product of p and q as a new linked list and print product
    productPoly = polyP.mult(polyQ)
    print(productPoly)


if __name__ == "__main__":
    main()
